### ISSUE TITLE
The start of CleanUP

### ISSUE THREAD

**Issue by Iyronic** [falceso/CleanUP#4]
###  CleanUP issues
Is CleanUP working on your creative server still, @falceso? @xYuchi might've made some mistakes when creating the configuration. Watch [this](https://www.youtube.com/watch?v=NWQoORxhmX8) for information on the configuration - BukkitLib/Aero might not work with this and you might have to restart.

- @Iyronic

**Comment by falceso** [comment]
Hello!
I am not really going to continue this plugin anymore because it's to basic. I'm currently working on a few more complex plugins.
Thanks
@falceso

**Comment by falceso** [comment]
Also @xyuchi is no longer available for a while. @xyuchi has a bit of a type 2 cancer atm.

**Comment by falceso** [comment]
I can assign you to this issue if you want :) I might make a new cleanup plugin soon.

**Comment by Ultra-DEV** [comment]
I was new to configuring - now lettme fix the issue.

**Comment by Ultra-DEV** [comment]
@falceso please close this issue.

**Comment by Ultra-DEV** [comment]
#2

**Comment by falceso** [comment]
Closed #2
